System\Applications\Code\Tables\Applications:
  table: system_applications
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      name: title
      type: string
      length: 255
      nullable: false
    name:
      name: name
      type: string
      length: 255
      nullable: false
    description:
      name: description
      type: text
      nullable: true
    path:
      name: path
      type: string
      length: 255
      nullable: false
    icon:
      name: icon
      type: string
      length: 255
      nullable: true
    version:
      name: version
      type: string
      length: 255
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: true
    date_created:
      name: date_created
      type: datetime
      nullable: true
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: true
    date_modified:
      name: date_modified
      type: datetime
      nullable: true
  indexes:
    name_index:
      columns: [name]
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
