System\Settings\Code\Tables\Settings:
  table: system_settings
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    subset_id:
      name: subset_id
      type: integer
      length: '11'
      nullable: true
    name:
      name: name
      type: string
      length: 255
      nullable: false
    value:
      name: value
      type: string
      length: 255
      nullable: false
    extension_path:
      name: extension_path
      type: string
      length: 255
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: false
    date_created:
      name: date_created
      type: datetime
      nullable: false
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: false
    date_modified:
      name: date_modified
      type: datetime
      nullable: false
  indexes:
    subset_id_index:
      columns: [subset_id]
    name_index:
      columns: [name]
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
